name: Deploy a Net Project

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Self
        uses: actions/checkout@v4
      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: dornet restore
        run: dotnet restore -f PartsUnlimited-aspnet45/PartsUnlimited.sln
      - name: dotnet build
        run:  dotnet build  --no-restore
        continue-on-error: true
      - name: Dotnet tests
        uses: EasyDesk/action-dotnet-test@v1.0.0
        with:
          build-configuration: Release
          path: PartsUnlimited-aspnet45/PartsUnlimited.sln
          skip-build: true
          
      
  
